### ISSUE TITLE
Check if extracted text ought to include JSON text

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-index#5]
The extracted text is the same as in standard-search (see https://github.com/OpenDataServices/standard-search/issues/29).

However, we might not want to include JSON text or text from other directives.

The `data.json` file OCDS Index generates can be reviewed.

**Comment by yolile** [comment]
If the JSON key that someone could search is relevant in the documentation where it is mentioned, I think that probably it will appear also in the Markdown, so I think that it is fine to not include JSON texts in the results to avoid having too many non-related results, especially with some common keys as "tender", "ocid", etc

**Comment by jpmckinney** [comment]
Closed in a082325
